export const ACTIONS = {
  GET_BOOKS_LIST: 'GET_BOOKS_LIST',
  SET_BOOKS_OFFSET: 'SET_BOOKS_OFFSET',
  SET_SEARCH_AUTHOR: 'SET_SEARCH_AUTHOR',
  SET_SEARCH_TITLE: 'SET_SEARCH_TITLE',
  GET_BESTSELLER_BOOK_LIST: 'GET_BESTSELLER_BOOK_LIST',
  SET_USER_LOGIN: 'SET_USER_LOGIN',
};
