export const ACTIONS = {
  GET_BOOKS_LIST: 'GET_BOOKS_LIST',
  SET_BOOKS_OFFSET: 'SET_BOOKS_OFFSET',
  SET_SEARCH_AUTHOR: 'SET_SEARCH_AUTHOR',
  SET_SEARCH_TITLE: 'SET_SEARCH_TITLE',
  GET_BESTSELLER_BOOK_LIST: 'GET_BESTSELLER_BOOK_LIST',
  REGISTER_FAIL: 'REGISTER_FAIL',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
};
